# CAR Trade Loader
CAR_TRADE_RECORDTYPE = "RecordType"               # Buy/Sell
CAR_TRADE_RECORDACTION = "RecordAction"
CAR_TRADE_KEYVALUE2 = "KeyValue2"                 # scrip name
CAR_TRADE_KEYVALUE = "KeyValue.KeyName"
CAR_TRADE_USERTRANID1 = "UserTranId1"
CAR_TRADE_PORTFOLIO = "Portfolio"
CAR_TRADE_LOCATIONACCOUNT = "LocationAccount"
CAR_TRADE_STRATEGY = "Strategy"
CAR_TRADE_INVESTMENT = "Investment"               # scrip name
CAR_TRADE_BROKER = "Broker"
CAR_TRADE_EVENTDATE = "EventDate"                 # Date
CAR_TRADE_SETTLEDATE = "SettleDate"               # Date
CAR_TRADE_ACTUALSETTLEDATE = "ActualSettleDate"   # Date
CAR_TRADE_QUANTITY = "Quantity"                   # Qty
CAR_TRADE_PRICE = "Price"                         # Rate
CAR_TRADE_PRICEDENOMINATION = "PriceDenomination" 
CAR_TRADE_COUNTERINVESTMENT = "CounterInvestment"
CAR_TRADE_NETINVESTMENTAMOUNT = "NetInvestmentAmount"
CAR_TRADE_NETCOUNTERAMOUNT = "NetCounterAmount"
CAR_TRADE_TRADEFX = "TradeFX"
CAR_TRADE_CONTRACTFXRATENUMERATOR = "ContractFxRateNumerator"
CAR_TRADE_CONTRACTFXRATEDENOMINATOR = "ContractFxRateDenominator"
CAR_TRADE_CONTRACTFXRATE = "ContractFxRate"
CAR_TRADE_NOTIONALAMOUNT = "NotionalAmount"
CAR_TRADE_FUNDSTRUCTURE = "FundStructure"
CAR_TRADE_SPOTDATE = "SpotDate"
CAR_TRADE_PRICEDIRECTLY = "PriceDirectly"
CAR_TRADE_COUNTERFXDENOMINATION = "CounterFXDenomination"
CAR_TRADE_COUNTERTDATEFX = "CounterTDateFx"
CAR_TRADE_ACCRUEDINTEREST = "AccruedInterest"
CAR_TRADE_INVESTMENTACCRUEDINTEREST = "InvestmentAccruedInterest"
CAR_TRADE_TRADEEXPENSES_EXPENSENUMBER = "TradeExpenses.ExpenseNumber"
CAR_TRADE_TRADEEXPENSES_EXPENSECODE = "TradeExpenses.ExpenseCode"
CAR_TRADE_TRADEEXPENSES_EXPENSEAMT = "TradeExpenses.ExpenseAmt"
CAR_TRADE_NONCAPEXPENSES_NONCAPNUMBER = "NonCapExpenses.NonCapNumber"
CAR_TRADE_NONCAPEXPENSES_NONCAPEXPENSECODE = "NonCapExpenses.NonCapExpenseCode"
CAR_TRADE_NONCAPEXPENSES_NONCAPAMOUNT = "NonCapExpenses.NonCapAmount"
CAR_TRADE_NONCAPEXPENSES_NONCAPCURRENCY = "NonCapExpenses.NonCapCurrency"
CAR_TRADE_NONCAPEXPENSES_LOCATIONACCOUNT = "NonCapExpenses.LocationAccount"
CAR_TRADE_NONCAPEXPENSES_NONCAPLIABILITYCODE = "NonCapExpenses.NonCapLiabilityCode"
CAR_TRADE_NONCAPEXPENSES_NONCAPPAYMENTTYPE = "NonCapExpenses.NonCapPaymentType"

CAR_TRADE_HEADERS = [CAR_TRADE_RECORDTYPE,CAR_TRADE_RECORDACTION,CAR_TRADE_KEYVALUE2,CAR_TRADE_KEYVALUE,CAR_TRADE_USERTRANID1,CAR_TRADE_PORTFOLIO,CAR_TRADE_LOCATIONACCOUNT,CAR_TRADE_STRATEGY,CAR_TRADE_INVESTMENT,CAR_TRADE_BROKER,CAR_TRADE_EVENTDATE,CAR_TRADE_SETTLEDATE,CAR_TRADE_ACTUALSETTLEDATE,CAR_TRADE_QUANTITY,CAR_TRADE_PRICE,CAR_TRADE_PRICEDENOMINATION,CAR_TRADE_COUNTERINVESTMENT,CAR_TRADE_NETINVESTMENTAMOUNT,CAR_TRADE_NETCOUNTERAMOUNT,CAR_TRADE_TRADEFX,CAR_TRADE_CONTRACTFXRATENUMERATOR,CAR_TRADE_CONTRACTFXRATEDENOMINATOR,CAR_TRADE_CONTRACTFXRATE,CAR_TRADE_NOTIONALAMOUNT,CAR_TRADE_FUNDSTRUCTURE,CAR_TRADE_SPOTDATE,CAR_TRADE_PRICEDIRECTLY,CAR_TRADE_COUNTERFXDENOMINATION,CAR_TRADE_COUNTERTDATEFX,CAR_TRADE_ACCRUEDINTEREST,CAR_TRADE_INVESTMENTACCRUEDINTEREST,CAR_TRADE_TRADEEXPENSES_EXPENSENUMBER,CAR_TRADE_TRADEEXPENSES_EXPENSECODE,CAR_TRADE_TRADEEXPENSES_EXPENSEAMT,CAR_TRADE_NONCAPEXPENSES_NONCAPNUMBER,CAR_TRADE_NONCAPEXPENSES_NONCAPEXPENSECODE,CAR_TRADE_NONCAPEXPENSES_NONCAPAMOUNT,CAR_TRADE_NONCAPEXPENSES_NONCAPCURRENCY,CAR_TRADE_NONCAPEXPENSES_LOCATIONACCOUNT,CAR_TRADE_NONCAPEXPENSES_NONCAPLIABILITYCODE,CAR_TRADE_NONCAPEXPENSES_NONCAPPAYMENTTYPE]

# option_security
OPTION_CODE = "Code"                                   # scrip name
OPTION_KEYVALUE = "KeyValue"                           # scrip name
OPTION_DESCRIPTION = "Description"                     # scrip name
OPTION_EXTENDEDDESCRIPTION = "ExtendedDescription"     # scrip name
OPTION_EXCHANGE = "Exchange"                           #
OPTION_ISSUER = "Issuer"                               # 
OPTION_TICKER = "Ticker"                               #
OPTION_CUSIP = "Cusip"                                 #
OPTION_SEDOL = "Sedol"                                 #
OPTION_ISIN = "Isin"                                   #
OPTION_RICCODE = "Riccode"                             #
OPTION_ALTKEY1 = "AltKey1"                             #
OPTION_ALTKEY2 = "AltKey2"                             #
OPTION_BLOOMBERGID = "BloombergID"                     #
OPTION_BLOOMBERGTICKER = "BloombergTicker"             #
OPTION_BLOOMBERGUNIQUEID = "BloombergUniqueID"         #
OPTION_BLOOMBERGMARKETSECTOR = "BloombergMarketSector" #
OPTION_SETTLEDAYS = "SettleDays"                       #
OPTION_PRICINGFACTOR = "PricingFactor"                 #
OPTION_TRADINGFACTOR = "TradingFactor"                 # TradingSize
OPTION_CURRENTPRICEDAYRANGE = "CurrentPriceDayRange"
OPTION_ASSETTYPE = "AssetType"
OPTION_INVESTMENTTYPE = "InvestmentType"
OPTION_PRICEDENOMINATION = "PriceDenomination"
OPTION_BIFURCATIONCURRENCY = "BifurcationCurrency"
OPTION_PRINCIPALCURRENCY = "PrincipalCurrency"
OPTION_INCOMECURRENCY = "IncomeCurrency"
OPTION_RISKCURRENCY = "RiskCurrency"
OPTION_ISSUECOUNTRY = "IssueCountry"
OPTION_WITHHOLDINGTAXTYPE = "WithholdingTaxType"
OPTION_QDIELIGIBILITYFLAG = "QDIEligibilityFlag"
OPTION_SHARESOUTSTANDING = "SharesOutstanding"
OPTION_BETA = "Beta"
OPTION_SUBINDUSTRY = "SubIndustry"
OPTION_SUBINDUSTRY2 = "SubIndustry2"
OPTION_NONDELIVERABLECURRENCYFLAG = "NonDeliverableCurrencyFlag"
OPTION_QUANTITYPRECISION = "QuantityPrecision"
OPTION_INVESTMENTCROSSZERO = "InvestmentCrossZero"
OPTION_UNDERLYINGINVESTMENT = "UnderlyingInvestment" # Underlying
OPTION_EXPIREDATE = "ExpireDate"                     # Expiry
OPTION_STRIKEPRICE = "StrikePrice"                   # Strike Price
OPTION_PRICEBYPREFERENCE = "PriceByPreference"
OPTION_FORWARDPRICEINTERPOLATEFLAG = "ForwardPriceInterpolateFlag"
OPTION_SECFEESCHEDULE = "SecFeeSchedule"
OPTION_SECELIGIBLEFLAG = "SecEligibleFlag"
OPTION_WASHSALESELIGIBLE = "WashSalesEligible"
OPTION_EXERCISESTYLE = "ExerciseStyle"
OPTION_PUTCALLFLAG = "PutCallFlag"                   # Call Put Flag
OPTION_PRICINGPRECISION = "PricingPrecision"         
OPTION_CASHSETTLEDFLAG = "CashSettledFlag"

OPTION_HEADER = [OPTION_CODE,OPTION_KEYVALUE,OPTION_DESCRIPTION,OPTION_EXTENDEDDESCRIPTION,OPTION_EXCHANGE,OPTION_ISSUER,OPTION_TICKER,OPTION_CUSIP,OPTION_SEDOL,OPTION_ISIN,OPTION_RICCODE,OPTION_ALTKEY1,OPTION_ALTKEY2,OPTION_BLOOMBERGID,OPTION_BLOOMBERGTICKER,OPTION_BLOOMBERGUNIQUEID,OPTION_BLOOMBERGMARKETSECTOR,OPTION_SETTLEDAYS,OPTION_PRICINGFACTOR,OPTION_TRADINGFACTOR,OPTION_CURRENTPRICEDAYRANGE,OPTION_ASSETTYPE,OPTION_INVESTMENTTYPE,OPTION_PRICEDENOMINATION,OPTION_BIFURCATIONCURRENCY,OPTION_PRINCIPALCURRENCY,OPTION_INCOMECURRENCY,OPTION_RISKCURRENCY,OPTION_ISSUECOUNTRY,OPTION_WITHHOLDINGTAXTYPE,OPTION_QDIELIGIBILITYFLAG,OPTION_SHARESOUTSTANDING,OPTION_BETA,OPTION_SUBINDUSTRY,OPTION_SUBINDUSTRY2,OPTION_NONDELIVERABLECURRENCYFLAG,OPTION_QUANTITYPRECISION,OPTION_INVESTMENTCROSSZERO,OPTION_UNDERLYINGINVESTMENT,OPTION_EXPIREDATE,OPTION_STRIKEPRICE,OPTION_PRICEBYPREFERENCE,OPTION_FORWARDPRICEINTERPOLATEFLAG,OPTION_SECFEESCHEDULE,OPTION_SECELIGIBLEFLAG,OPTION_WASHSALESELIGIBLE,OPTION_EXERCISESTYLE,OPTION_PUTCALLFLAG,OPTION_PRICINGPRECISION,OPTION_CASHSETTLEDFLAG]


# aafspl_car_future
AAFSPL_CODE = "Code"
AAFSPL_KEYVALUE = "KeyValue"
AAFSPL_DESCRIPTION = "Description"
AAFSPL_EXTENDEDDESCRIPTION = "ExtendedDescription"
AAFSPL_EXCHANGE = "Exchange"
AAFSPL_ISSUER = "Issuer"
AAFSPL_TICKER = "Ticker"
AAFSPL_CUSIP = "Cusip"
AAFSPL_SEDOL = "Sedol"
AAFSPL_ISIN = "Isin"
AAFSPL_ALTKEY1 = "AltKey1"
AAFSPL_ALTKEY2 = "AltKey2"
AAFSPL_BLOOMBERGID = "BloombergID"
AAFSPL_BLOOMBERGTICKER = "BloombergTicker"
AAFSPL_BLOOMBERGUNIQUEID = "BloombergUniqueID"
AAFSPL_BLOOMBERGMARKETSECTOR = "BloombergMarketSector"
AAFSPL_SETTLEDAYS = "SettleDays"
AAFSPL_PRICINGFACTOR = "PricingFactor"
AAFSPL_TRADINGFACTOR = "TradingFactor"
AAFSPL_CURRENTPRICEDAYRANGE = "CurrentPriceDayRange"
AAFSPL_ASSETTYPE = "AssetType"
AAFSPL_INVESTMENTTYPE = "InvestmentType"
AAFSPL_PRICEDENOMINATION = "PriceDenomination"
AAFSPL_BIFURCATIONCURRENCY = "BifurcationCurrency"
AAFSPL_PRINCIPALCURRENCY = "PrincipalCurrency"
AAFSPL_INCOMECURRENCY = "IncomeCurrency"
AAFSPL_RISKCURRENCY = "RiskCurrency"
AAFSPL_ISSUECOUNTRY = "IssueCountry"
AAFSPL_WITHHOLDINGTAXTYPE = "WithholdingTaxType"
AAFSPL_QDIELIGIBILITYFLAG = "QDIEligibilityFlag"
AAFSPL_SHARESOUTSTANDING = "SharesOutstanding"
AAFSPL_SUBINDUSTRY = "SubIndustry"
AAFSPL_SUBINDUSTRY2 = "SubIndustry2"
AAFSPL_QUANTITYPRECISION = "QuantityPrecision"
AAFSPL_INVESTMENTCROSSZERO = "InvestmentCrossZero"
AAFSPL_UNDERLYINGINVESTMENT = "UnderlyingInvestment"
AAFSPL_EXPIREDATE = "ExpireDate"
AAFSPL_STRIKEPRICE = "StrikePrice"
AAFSPL_PRICEBYPREFERENCE = "PriceByPreference"
AAFSPL_FORWARDPRICEINTERPOLATEFLAG = "ForwardPriceInterpolateFlag"
AAFSPL_PRICINGPRECISION = "PricingPrecision"
AAFSPL_FIRSTMARKDATE = "FirstMarkDate"
AAFSPL_LASTMARKDATE = "LastMarkDate"
AAFSPL_PRICELIST = "PriceList"
AAFSPL_AUTOGENERATEMARKS = "AutoGenerateMarks"
AAFSPL_CASHSETTLEMENT = "CashSettlement"

AAFSPL_HEADER = [AAFSPL_CODE,AAFSPL_KEYVALUE,AAFSPL_DESCRIPTION,AAFSPL_EXTENDEDDESCRIPTION,AAFSPL_EXCHANGE,AAFSPL_ISSUER,AAFSPL_TICKER,AAFSPL_CUSIP,AAFSPL_SEDOL,AAFSPL_ISIN,AAFSPL_ALTKEY1,AAFSPL_ALTKEY2,AAFSPL_BLOOMBERGID,AAFSPL_BLOOMBERGTICKER,AAFSPL_BLOOMBERGUNIQUEID,AAFSPL_BLOOMBERGMARKETSECTOR,AAFSPL_SETTLEDAYS,AAFSPL_PRICINGFACTOR,AAFSPL_TRADINGFACTOR,AAFSPL_CURRENTPRICEDAYRANGE,AAFSPL_ASSETTYPE,AAFSPL_INVESTMENTTYPE,AAFSPL_PRICEDENOMINATION,AAFSPL_BIFURCATIONCURRENCY,AAFSPL_PRINCIPALCURRENCY,AAFSPL_INCOMECURRENCY,AAFSPL_RISKCURRENCY,AAFSPL_ISSUECOUNTRY,AAFSPL_WITHHOLDINGTAXTYPE,AAFSPL_QDIELIGIBILITYFLAG,AAFSPL_SHARESOUTSTANDING,AAFSPL_SUBINDUSTRY,AAFSPL_SUBINDUSTRY2,AAFSPL_QUANTITYPRECISION,AAFSPL_INVESTMENTCROSSZERO,AAFSPL_UNDERLYINGINVESTMENT,AAFSPL_EXPIREDATE,AAFSPL_STRIKEPRICE,AAFSPL_PRICEBYPREFERENCE,AAFSPL_FORWARDPRICEINTERPOLATEFLAG,AAFSPL_PRICINGPRECISION,AAFSPL_FIRSTMARKDATE,AAFSPL_LASTMARKDATE,AAFSPL_PRICELIST,AAFSPL_AUTOGENERATEMARKS,AAFSPL_CASHSETTLEMENT]

FORMAT_1 = "Format 1"
FORMAT_2 = "Format 2"
BHAVCOPY = "BhavCopy"

# geneva Headers
PORTFOLIO = "Portfolio"
INVESTMENT = "Investment"
INVESTMENT_DESCRIPTION = "Investment Description"
SETTLED_QUANTITY = "Settled Quantity"
UNIT_COST = "Unit Cost"
CURRENCY = "Currency"
COST_LOCAL = "Cost Local"
MARKET_PRICE_LOCAL = "Market Price Local"
COST_BOOK = "Cost Book"
MARKET_VALUE_LOCAL = "Market Value Local"
UNIQUECODE = "UniqueCode"
MARKET_VALUE_BOOK = "Market Value Book"
UNREALIZED_G_L_BOOK = "Unrealized G/L Book"
ACCRUED_INTEREST_LOCAL = "Accrued Interest Local"
CUST_ACCOUNT = "Cust Account"
STRATEGY = "Strategy"
FUND_NAME_IN_CUSTODY_HOLDING = "Fund Name IN Custody Holding"
NSE_PRICE = "Nse Price"
DIFF = "Diff"


# single-constant assignments
REGULAR_HOLDINGS_SOURCE_NAME = "Regular_Holdings.Source.Name"
REGULAR_HOLDINGS_DATE = "Regular_Holdings.Date"
REGULAR_HOLDINGS_EXCHANGE = "Regular_Holdings.Exchange"
REGULAR_HOLDINGS_CLIENTNAME = "Regular_Holdings.ClientName"
REGULAR_HOLDINGS_CLIENTCODE = "Regular_Holdings.ClientCode"
REGULAR_HOLDINGS_OPTIONTYPE = "Regular_Holdings.OptionType"
REGULAR_HOLDINGS_UNDERLYINGCODE = "Regular_Holdings.UnderlyingCode"
REGULAR_HOLDINGS_UNDERLYINGNAME = "Regular_Holdings.UnderlyingName"
REGULAR_HOLDINGS_INSTRUMENTTYPE = "Regular_Holdings.InstrumentType"
REGULAR_HOLDINGS_STRIKEPRICE = "Regular_Holdings.StrikePrice"
REGULAR_HOLDINGS_EXPIRYDATE = "Regular_Holdings.ExpiryDate"
REGULAR_HOLDINGS_OPENBUY = "Regular_Holdings.OpenBuy"
REGULAR_HOLDINGS_OPENSELL = "Regular_Holdings.OpenSell"
REGULAR_HOLDINGS_TRADEDSELL = "Regular_Holdings.TradedSell"
REGULAR_HOLDINGS_TRADEDBUY = "Regular_Holdings.TradedBuy"
REGULAR_HOLDINGS_DAYBUYVALUE = "Regular_Holdings.DayBuyValue"
REGULAR_HOLDINGS_DAYSELLVALUE = "Regular_Holdings.DaySellValue"
REGULAR_HOLDINGS_EXCERCISEQTY = "Regular_Holdings.ExcerciseQty"
REGULAR_HOLDINGS_ALLOCATIONQTY = "Regular_Holdings.AllocationQty"
REGULAR_HOLDINGS_NETBUY = "Regular_Holdings.NetBuy"
REGULAR_HOLDINGS_NETSELL = "Regular_Holdings.NetSell"
REGULAR_HOLDINGS_CONTRACTSETTLEMENTPRICE = "Regular_Holdings.ContractSettlementPrice"
REGULAR_HOLDINGS_CLOSINGPRICE = "Regular_Holdings.ClosingPrice"
REGULAR_HOLDINGS_BLOOMBERGCD = "Regular_Holdings.BloombergCD"
REGULAR_HOLDINGS_CONCATENATE = "Regular_Holdings.Concatenate"
REGULAR_HOLDINGS_FUND_NAME_IN_GENEVA = "Regular_Holdings.Fund Name In Geneva"
REGULAR_HOLDINGS_UNIQUECODE = "Regular_Holdings.UniqueCode"
REGULAR_HOLDINGS_NETBUY_NETSELL = "Regular_Holdings.NetBuy-Netsell"
GENEVA_TRADED_QUANTITY = "Geneva Traded Quantity"
DIFFERENCE_QTY = "Difference Qty"

# dictionary mapping (useful for programmatic lookups)
REG_GENEVA_HEADERS_DICT = {
    "PORTFOLIO": PORTFOLIO,
    "INVESTMENT": INVESTMENT,
    "INVESTMENT_DESCRIPTION": INVESTMENT_DESCRIPTION,
    "SETTLED_QUANTITY": SETTLED_QUANTITY,
    "UNIT_COST": UNIT_COST,
    "CURRENCY": CURRENCY,
    "COST_LOCAL": COST_LOCAL,
    "MARKET_PRICE_LOCAL": MARKET_PRICE_LOCAL,
    "COST_BOOK": COST_BOOK,
    "MARKET_VALUE_LOCAL": MARKET_VALUE_LOCAL,
    "UNIQUECODE": UNIQUECODE,
    "MARKET_VALUE_BOOK": MARKET_VALUE_BOOK,
    "UNREALIZED_G_L_BOOK": UNREALIZED_G_L_BOOK,
    "ACCRUED_INTEREST_LOCAL": ACCRUED_INTEREST_LOCAL,
    "CUST_ACCOUNT": CUST_ACCOUNT,
    "STRATEGY": STRATEGY,
    "FUND_NAME_IN_CUSTODY_HOLDING": FUND_NAME_IN_CUSTODY_HOLDING,
    "NSE_PRICE": NSE_PRICE,
    "DIFF": DIFF,
    "REGULAR_HOLDINGS_SOURCE_NAME": REGULAR_HOLDINGS_SOURCE_NAME,
    "REGULAR_HOLDINGS_DATE": REGULAR_HOLDINGS_DATE,
    "REGULAR_HOLDINGS_EXCHANGE": REGULAR_HOLDINGS_EXCHANGE,
    "REGULAR_HOLDINGS_CLIENTNAME": REGULAR_HOLDINGS_CLIENTNAME,
    "REGULAR_HOLDINGS_CLIENTCODE": REGULAR_HOLDINGS_CLIENTCODE,
    "REGULAR_HOLDINGS_OPTIONTYPE": REGULAR_HOLDINGS_OPTIONTYPE,
    "REGULAR_HOLDINGS_UNDERLYINGCODE": REGULAR_HOLDINGS_UNDERLYINGCODE,
    "REGULAR_HOLDINGS_UNDERLYINGNAME": REGULAR_HOLDINGS_UNDERLYINGNAME,
    "REGULAR_HOLDINGS_INSTRUMENTTYPE": REGULAR_HOLDINGS_INSTRUMENTTYPE,
    "REGULAR_HOLDINGS_STRIKEPRICE": REGULAR_HOLDINGS_STRIKEPRICE,
    "REGULAR_HOLDINGS_EXPIRYDATE": REGULAR_HOLDINGS_EXPIRYDATE,
    "REGULAR_HOLDINGS_OPENBUY": REGULAR_HOLDINGS_OPENBUY,
    "REGULAR_HOLDINGS_OPENSELL": REGULAR_HOLDINGS_OPENSELL,
    "REGULAR_HOLDINGS_TRADEDSELL": REGULAR_HOLDINGS_TRADEDSELL,
    "REGULAR_HOLDINGS_TRADEDBUY": REGULAR_HOLDINGS_TRADEDBUY,
    "REGULAR_HOLDINGS_DAYBUYVALUE": REGULAR_HOLDINGS_DAYBUYVALUE,
    "REGULAR_HOLDINGS_DAYSELLVALUE": REGULAR_HOLDINGS_DAYSELLVALUE,
    "REGULAR_HOLDINGS_EXCERCISEQTY": REGULAR_HOLDINGS_EXCERCISEQTY,
    "REGULAR_HOLDINGS_ALLOCATIONQTY": REGULAR_HOLDINGS_ALLOCATIONQTY,
    "REGULAR_HOLDINGS_NETBUY": REGULAR_HOLDINGS_NETBUY,
    "REGULAR_HOLDINGS_NETSELL": REGULAR_HOLDINGS_NETSELL,
    "REGULAR_HOLDINGS_CONTRACTSETTLEMENTPRICE": REGULAR_HOLDINGS_CONTRACTSETTLEMENTPRICE,
    "REGULAR_HOLDINGS_CLOSINGPRICE": REGULAR_HOLDINGS_CLOSINGPRICE,
    "REGULAR_HOLDINGS_BLOOMBERGCD": REGULAR_HOLDINGS_BLOOMBERGCD,
    "REGULAR_HOLDINGS_CONCATENATE": REGULAR_HOLDINGS_CONCATENATE,
    "REGULAR_HOLDINGS_FUND_NAME_IN_GENEVA": REGULAR_HOLDINGS_FUND_NAME_IN_GENEVA,
    "REGULAR_HOLDINGS_UNIQUECODE": REGULAR_HOLDINGS_UNIQUECODE,
    "REGULAR_HOLDINGS_NETBUY_NETSELL": REGULAR_HOLDINGS_NETBUY_NETSELL,
    "GENEVA_TRADED_QUANTITY": GENEVA_TRADED_QUANTITY,
    "DIFFERENCE_QTY": DIFFERENCE_QTY,
}

REG_GENEVA_HEADER_LIST = [
    PORTFOLIO,
    INVESTMENT,
    INVESTMENT_DESCRIPTION,
    SETTLED_QUANTITY,
    UNIT_COST,
    CURRENCY,
    COST_LOCAL,
    MARKET_PRICE_LOCAL,
    COST_BOOK,
    MARKET_VALUE_LOCAL,
    UNIQUECODE,
    MARKET_VALUE_BOOK,
    UNREALIZED_G_L_BOOK,
    ACCRUED_INTEREST_LOCAL,
    CUST_ACCOUNT,
    STRATEGY,
    FUND_NAME_IN_CUSTODY_HOLDING,
    NSE_PRICE,
    DIFF,
    REGULAR_HOLDINGS_SOURCE_NAME,
    REGULAR_HOLDINGS_DATE,
    REGULAR_HOLDINGS_EXCHANGE,
    REGULAR_HOLDINGS_CLIENTNAME,
    REGULAR_HOLDINGS_CLIENTCODE,
    REGULAR_HOLDINGS_OPTIONTYPE,
    REGULAR_HOLDINGS_UNDERLYINGCODE,
    REGULAR_HOLDINGS_UNDERLYINGNAME,
    REGULAR_HOLDINGS_INSTRUMENTTYPE,
    REGULAR_HOLDINGS_STRIKEPRICE,
    REGULAR_HOLDINGS_EXPIRYDATE,
    REGULAR_HOLDINGS_OPENBUY,
    REGULAR_HOLDINGS_OPENSELL,
    REGULAR_HOLDINGS_TRADEDSELL,
    REGULAR_HOLDINGS_TRADEDBUY,
    REGULAR_HOLDINGS_DAYBUYVALUE,
    REGULAR_HOLDINGS_DAYSELLVALUE,
    REGULAR_HOLDINGS_EXCERCISEQTY,
    REGULAR_HOLDINGS_ALLOCATIONQTY,
    REGULAR_HOLDINGS_NETBUY,
    REGULAR_HOLDINGS_NETSELL,
    REGULAR_HOLDINGS_CONTRACTSETTLEMENTPRICE,
    REGULAR_HOLDINGS_CLOSINGPRICE,
    REGULAR_HOLDINGS_BLOOMBERGCD,
    REGULAR_HOLDINGS_CONCATENATE,
    REGULAR_HOLDINGS_FUND_NAME_IN_GENEVA,
    REGULAR_HOLDINGS_UNIQUECODE,
    REGULAR_HOLDINGS_NETBUY_NETSELL,
    GENEVA_TRADED_QUANTITY,
    DIFFERENCE_QTY,
]


# single-constant assignments
CDS_HOLDINGS_SOURCE_NAME = "CDS_Holdings.Source.Name"
CDS_HOLDINGS_DATE = "CDS_Holdings.Date"
CDS_HOLDINGS_QUANTITYUNIT = "CDS_Holdings.QuantityUnit"
CDS_HOLDINGS_EXCHANGE = "CDS_Holdings.Exchange"
CDS_HOLDINGS_CLIENTCODE = "CDS_Holdings.ClientCode"
CDS_HOLDINGS_TRADINGCODE = "CDS_Holdings.TradingCode"
CDS_HOLDINGS_UNDERLYINGCODE = "CDS_Holdings.UnderlyingCode"
CDS_HOLDINGS_CLIENTNAME = "CDS_Holdings.ClientName"
CDS_HOLDINGS_UNDERLYINGNAME = "CDS_Holdings.UnderlyingName"
CDS_HOLDINGS_INSTRUMENTTYPE = "CDS_Holdings.InstrumentType"
CDS_HOLDINGS_EXPIRYDATE = "CDS_Holdings.ExpiryDate"
CDS_HOLDINGS_OPTIONTYPE = "CDS_Holdings.OptionType"
CDS_HOLDINGS_STRIKEPRICE = "CDS_Holdings.StrikePrice"
CDS_HOLDINGS_OPENBUY = "CDS_Holdings.OpenBuy"
CDS_HOLDINGS_OPENSELL = "CDS_Holdings.OpenSell"
CDS_HOLDINGS_TRADEDBUY = "CDS_Holdings.TradedBuy"
CDS_HOLDINGS_DAYBUYVALUE = "CDS_Holdings.DayBuyValue"
CDS_HOLDINGS_TRADEDSELL = "CDS_Holdings.TradedSell"
CDS_HOLDINGS_DAYSELLVALUE = "CDS_Holdings.DaySellValue"
CDS_HOLDINGS_EXCERCISEQTY = "CDS_Holdings.ExcerciseQty"
CDS_HOLDINGS_ALLOCATIONQTY = "CDS_Holdings.AllocationQty"
CDS_HOLDINGS_NETBUY = "CDS_Holdings.NetBuy"
CDS_HOLDINGS_NETSELL = "CDS_Holdings.NetSell"
CDS_HOLDINGS_CONTRACTSETTLEMENTPRICE = "CDS_Holdings.ContractSettlementPrice"
CDS_HOLDINGS_SETTLEMENT_PRICE = "CDS_Holdings.Settlement Price"
CDS_HOLDINGS_BLOOMBERGCODES = "CDS_Holdings.BloombergCodes"
CDS_HOLDINGS_CONCATENATE = "CDS_Holdings.Concatenate"
CDS_HOLDINGS_FUND_NAME_IN_GENEVA = "CDS_Holdings.Fund Name In Geneva"
CDS_HOLDINGS_UNIQUECODE = "CDS_Holdings.UniqueCode"
CDS_HOLDINGS_NETBUY_NETSELL = "CDS_Holdings.Netbuy-Netsell"
GENEVA_TRADED_QUANTITY = "Geneva Traded Quantity"
DIFFERENCE = "Difference"

# dictionary mapping (useful for programmatic lookups)
CDS_GENEVA_HEADER_DICT = {
    "PORTFOLIO": PORTFOLIO,
    "INVESTMENT": INVESTMENT,
    "INVESTMENT_DESCRIPTION": INVESTMENT_DESCRIPTION,
    "SETTLED_QUANTITY": SETTLED_QUANTITY,
    "UNIT_COST": UNIT_COST,
    "CURRENCY": CURRENCY,
    "COST_LOCAL": COST_LOCAL,
    "MARKET_PRICE_LOCAL": MARKET_PRICE_LOCAL,
    "COST_BOOK": COST_BOOK,
    "MARKET_VALUE_LOCAL": MARKET_VALUE_LOCAL,
    "UNIQUECODE": UNIQUECODE,
    "MARKET_VALUE_BOOK": MARKET_VALUE_BOOK,
    "UNREALIZED_G_L_BOOK": UNREALIZED_G_L_BOOK,
    "ACCRUED_INTEREST_LOCAL": ACCRUED_INTEREST_LOCAL,
    "CUST_ACCOUNT": CUST_ACCOUNT,
    "STRATEGY": STRATEGY,
    "FUND_NAME_IN_CUSTODY_HOLDING": FUND_NAME_IN_CUSTODY_HOLDING,
    "NSE_PRICE": NSE_PRICE,
    "DIFF": DIFF,
    "CDS_HOLDINGS_SOURCE_NAME": CDS_HOLDINGS_SOURCE_NAME,
    "CDS_HOLDINGS_DATE": CDS_HOLDINGS_DATE,
    "CDS_HOLDINGS_QUANTITYUNIT": CDS_HOLDINGS_QUANTITYUNIT,
    "CDS_HOLDINGS_EXCHANGE": CDS_HOLDINGS_EXCHANGE,
    "CDS_HOLDINGS_CLIENTCODE": CDS_HOLDINGS_CLIENTCODE,
    "CDS_HOLDINGS_TRADINGCODE": CDS_HOLDINGS_TRADINGCODE,
    "CDS_HOLDINGS_UNDERLYINGCODE": CDS_HOLDINGS_UNDERLYINGCODE,
    "CDS_HOLDINGS_CLIENTNAME": CDS_HOLDINGS_CLIENTNAME,
    "CDS_HOLDINGS_UNDERLYINGNAME": CDS_HOLDINGS_UNDERLYINGNAME,
    "CDS_HOLDINGS_INSTRUMENTTYPE": CDS_HOLDINGS_INSTRUMENTTYPE,
    "CDS_HOLDINGS_EXPIRYDATE": CDS_HOLDINGS_EXPIRYDATE,
    "CDS_HOLDINGS_OPTIONTYPE": CDS_HOLDINGS_OPTIONTYPE,
    "CDS_HOLDINGS_STRIKEPRICE": CDS_HOLDINGS_STRIKEPRICE,
    "CDS_HOLDINGS_OPENBUY": CDS_HOLDINGS_OPENBUY,
    "CDS_HOLDINGS_OPENSELL": CDS_HOLDINGS_OPENSELL,
    "CDS_HOLDINGS_TRADEDBUY": CDS_HOLDINGS_TRADEDBUY,
    "CDS_HOLDINGS_DAYBUYVALUE": CDS_HOLDINGS_DAYBUYVALUE,
    "CDS_HOLDINGS_TRADEDSELL": CDS_HOLDINGS_TRADEDSELL,
    "CDS_HOLDINGS_DAYSELLVALUE": CDS_HOLDINGS_DAYSELLVALUE,
    "CDS_HOLDINGS_EXCERCISEQTY": CDS_HOLDINGS_EXCERCISEQTY,
    "CDS_HOLDINGS_ALLOCATIONQTY": CDS_HOLDINGS_ALLOCATIONQTY,
    "CDS_HOLDINGS_NETBUY": CDS_HOLDINGS_NETBUY,
    "CDS_HOLDINGS_NETSELL": CDS_HOLDINGS_NETSELL,
    "CDS_HOLDINGS_CONTRACTSETTLEMENTPRICE": CDS_HOLDINGS_CONTRACTSETTLEMENTPRICE,
    "CDS_HOLDINGS_SETTLEMENT_PRICE": CDS_HOLDINGS_SETTLEMENT_PRICE,
    "CDS_HOLDINGS_BLOOMBERGCODES": CDS_HOLDINGS_BLOOMBERGCODES,
    "CDS_HOLDINGS_CONCATENATE": CDS_HOLDINGS_CONCATENATE,
    "CDS_HOLDINGS_FUND_NAME_IN_GENEVA": CDS_HOLDINGS_FUND_NAME_IN_GENEVA,
    "CDS_HOLDINGS_UNIQUECODE": CDS_HOLDINGS_UNIQUECODE,
    "CDS_HOLDINGS_NETBUY_NETSELL": CDS_HOLDINGS_NETBUY_NETSELL,
    "GENEVA_TRADED_QUANTITY": GENEVA_TRADED_QUANTITY,
    "DIFFERENCE": DIFFERENCE,
}

# optional: ordered header list for writing CSVs / DataFrame columns in original order
CDS_GENEVA_HEADER_LIST = [
    PORTFOLIO,
    INVESTMENT,
    INVESTMENT_DESCRIPTION,
    SETTLED_QUANTITY,
    UNIT_COST,
    CURRENCY,
    COST_LOCAL,
    MARKET_PRICE_LOCAL,
    COST_BOOK,
    MARKET_VALUE_LOCAL,
    UNIQUECODE,
    MARKET_VALUE_BOOK,
    UNREALIZED_G_L_BOOK,
    ACCRUED_INTEREST_LOCAL,
    CUST_ACCOUNT,
    STRATEGY,
    FUND_NAME_IN_CUSTODY_HOLDING,
    NSE_PRICE,
    DIFF,
    CDS_HOLDINGS_SOURCE_NAME,
    CDS_HOLDINGS_DATE,
    CDS_HOLDINGS_QUANTITYUNIT,
    CDS_HOLDINGS_EXCHANGE,
    CDS_HOLDINGS_CLIENTCODE,
    CDS_HOLDINGS_TRADINGCODE,
    CDS_HOLDINGS_UNDERLYINGCODE,
    CDS_HOLDINGS_CLIENTNAME,
    CDS_HOLDINGS_UNDERLYINGNAME,
    CDS_HOLDINGS_INSTRUMENTTYPE,
    CDS_HOLDINGS_EXPIRYDATE,
    CDS_HOLDINGS_OPTIONTYPE,
    CDS_HOLDINGS_STRIKEPRICE,
    CDS_HOLDINGS_OPENBUY,
    CDS_HOLDINGS_OPENSELL,
    CDS_HOLDINGS_TRADEDBUY,
    CDS_HOLDINGS_DAYBUYVALUE,
    CDS_HOLDINGS_TRADEDSELL,
    CDS_HOLDINGS_DAYSELLVALUE,
    CDS_HOLDINGS_EXCERCISEQTY,
    CDS_HOLDINGS_ALLOCATIONQTY,
    CDS_HOLDINGS_NETBUY,
    CDS_HOLDINGS_NETSELL,
    CDS_HOLDINGS_CONTRACTSETTLEMENTPRICE,
    CDS_HOLDINGS_SETTLEMENT_PRICE,
    CDS_HOLDINGS_BLOOMBERGCODES,
    CDS_HOLDINGS_CONCATENATE,
    CDS_HOLDINGS_FUND_NAME_IN_GENEVA,
    CDS_HOLDINGS_UNIQUECODE,
    CDS_HOLDINGS_NETBUY_NETSELL,
    GENEVA_TRADED_QUANTITY,
    DIFFERENCE,
]

MOTILAL_OSWAL_FINANCIAL_SERVICES_LIMITED = "Motilal Oswal Financial Services Limited"
TRUSTLINE_SECURITIES_LIMITED = "Trustline Securities Limited"
ACHINTYA_SECURITIES_PVT_LTD = "Achintya Securities Pvt. Ltd."

# asio sub fund 2 future_security
EXCHANGE = "Exchange"
ISSUER = "Issuer"
TICKER = "Ticker"
CUSIP = "Cusip"
SEDOL = "Sedol"
ISIN = "Isin"
ALTKEY1 = "AltKey1"
ALTKEY2 = "AltKey2"
BLOOMBERGID = "BloombergID"
BLOOMBERGTICKER = "BloombergTicker"
BLOOMBERGUNIQUEID = "BloombergUniqueID"
BLOOMBERGMARKETSECTOR = "BloombergMarketSector"
SETTLEDAYS = "SettleDays"
PRICINGFACTOR = "PricingFactor"
TRADINGFACTOR = "TradingFactor"
CURRENTPRICEDAYRANGE = "CurrentPriceDayRange"
ASSETTYPE = "AssetType"
INVESTMENTTYPE = "InvestmentType"
PRICEDENOMINATION = "PriceDenomination"
BIFURCATIONCURRENCY = "BifurcationCurrency"
PRINCIPALCURRENCY = "PrincipalCurrency"
INCOMECURRENCY = "IncomeCurrency"
RISKCURRENCY = "RiskCurrency"
ISSUECOUNTRY = "IssueCountry"
WITHHOLDINGTAXTYPE = "WithholdingTaxType"
QDIELIGIBILITYFLAG = "QDIEligibilityFlag"
SHARESOUTSTANDING = "SharesOutstanding"
SUBINDUSTRY = "SubIndustry"
SUBINDUSTRY2 = "SubIndustry2"
QUANTITYPRECISION = "QuantityPrecision"
INVESTMENTCROSSZERO = "InvestmentCrossZero"
PRICEBYPREFERENCE = "PriceByPreference"
FORWARDPRICEINTERPOLATEFLAG = "ForwardPriceInterpolateFlag"
PRICINGPRECISION = "PricingPrecision"
FIRSTMARKDATE = "FirstMarkDate"
LASTMARKDATE = "LastMarkDate"
PRICELIST = "PriceList"
AUTOGENERATEMARKS = "AutoGenerateMarks"
CASHSETTLEMENT = "CashSettlement"

# asio sub fund 2 option security
EXCHANGE = "Exchange"
ISSUER = "Issuer"
TICKER = "Ticker"
CUSIP = "Cusip"
SEDOL = "Sedol"
ISIN = "Isin"
RICCODE = "Riccode"
ALTKEY1 = "AltKey1"
ALTKEY2 = "AltKey2"
BLOOMBERGID = "BloombergID"
BLOOMBERGTICKER = "BloombergTicker"
BLOOMBERGUNIQUEID = "BloombergUniqueID"
BLOOMBERGMARKETSECTOR = "BloombergMarketSector"
SETTLEDAYS = "SettleDays"
PRICINGFACTOR = "PricingFactor"
TRADINGFACTOR = "TradingFactor"
CURRENTPRICEDAYRANGE = "CurrentPriceDayRange"
ASSETTYPE = "AssetType"
INVESTMENTTYPE = "InvestmentType"
PRICEDENOMINATION = "PriceDenomination"
BIFURCATIONCURRENCY = "BifurcationCurrency"
PRINCIPALCURRENCY = "PrincipalCurrency"
INCOMECURRENCY = "IncomeCurrency"
RISKCURRENCY = "RiskCurrency"
ISSUECOUNTRY = "IssueCountry"
WITHHOLDINGTAXTYPE = "WithholdingTaxType"
QDIELIGIBILITYFLAG = "QDIEligibilityFlag"
SHARESOUTSTANDING = "SharesOutstanding"
BETA = "Beta"
SUBINDUSTRY = "SubIndustry"
SUBINDUSTRY2 = "SubIndustry2"
NONDELIVERABLECURRENCYFLAG = "NonDeliverableCurrencyFlag"
QUANTITYPRECISION = "QuantityPrecision"
INVESTMENTCROSSZERO = "InvestmentCrossZero"
PRICEBYPREFERENCE = "PriceByPreference"
FORWARDPRICEINTERPOLATEFLAG = "ForwardPriceInterpolateFlag"
SECFEESCHEDULE = "SecFeeSchedule"
SECELIGIBLEFLAG = "SecEligibleFlag"
WASHSALESELIGIBLE = "WashSalesEligible"
EXERCISESTYLE = "ExerciseStyle"
PRICINGPRECISION = "PricingPrecision"
CASHSETTLEDFLAG = "CashSettledFlag"

# mtname - trustline, achintya, motilalal
RECORDACTION = "RecordAction"
KEYVALUE_KEYNAME = "KeyValue.KeyName"
USERTRANID1 = "UserTranId1"
PORTFOLIO = "Portfolio"
LOCATIONACCOUNT = "LocationAccount"
BROKER = "Broker"
PRICEDENOMINATION = "PriceDenomination"
COUNTERINVESTMENT = "CounterInvestment"
NETINVESTMENTAMOUNT = "NetInvestmentAmount"
NETCOUNTERAMOUNT = "NetCounterAmount"
TRADEFX = "tradeFX"
CONTRACTFXRATENUMERATOR = "ContractFxRateNumerator"
CONTRACTFXRATEDENOMINATOR = "ContractFxRateDenominator"
CONTRACTFXRATE = "ContractFxRate"
NOTIONALAMOUNT = "NotionalAmount"
FUNDSTRUCTURE2 = "FundStructure2"
SPOTDATE = "SpotDate"
PRICEDIRECTLY = "PriceDirectly"
COUNTERFXDENOMINATION = "CounterFXDenomination"
COUNTERTDATEFX = "CounterTDateFx"
ACCRUEDINTEREST = "AccruedInterest"
INVESTMENTACCRUEDINTEREST = "InvestmentAccruedInterest"
TRADEEXPENSES_EXPENSENUMBER = "TradeExpenses.ExpenseNumber"
TRADEEXPENSES_EXPENSECODE = "TradeExpenses.ExpenseCode"
TRADEEXPENSES_EXPENSEAMT = "TradeExpenses.ExpenseAmt"
NONCAPEXPENSES_NONCAPNUMBER = "NonCapExpenses.NonCapNumber"
NONCAPEXPENSES_NONCAPEXPENSECODE = "NonCapExpenses.NonCapExpenseCode"
NONCAPEXPENSES_NONCAPAMOUNT = "NonCapExpenses.NonCapAmount"
NONCAPEXPENSES_NONCAPCURRENCY = "NonCapExpenses.NonCapCurrency"
NONCAPEXPENSES_LOCATIONACCOUNT = "NonCapExpenses.LocationAccount"
NONCAPEXPENSES_NONCAPLIABILITYCODE = "NonCapExpenses.NonCapLiabilityCode"
NONCAPEXPENSES_NONCAPPAYMENTTYPE = "NonCapExpenses.NonCapPaymentType"

# ASIO SF 2 Trade Loader 01-09-2025 Trustline, ASIO SF 2 Trade Loader 01-09-2025.Achintya,  ASIO SF 2 Trade Loader 01-09-2025.Motilal
RECORDTYPE = "RecordType"
RECORDACTION = "RecordAction"
KEYVALUE_KEYNAME = "KeyValue"
KEYVALUE = "KeyValue.KeyName"
USERTRANID1 = "UserTranId1"
PORTFOLIO = "Portfolio"
LOCATIONACCOUNT = "LocationAccount"
STRATEGY = "Strategy"
INVESTMENT = "Investment"
BROKER = "Broker"
EVENTDATE = "EventDate"
SETTLEDATE = "SettleDate"
ACTUALSETTLEDATE = "ActualSettleDate"
QUANTITY = "Quantity"
PRICE = "Price"
PRICEDENOMINATION = "PriceDenomination"
COUNTERINVESTMENT = "CounterInvestment"
NETINVESTMENTAMOUNT = "NetInvestmentAmount"
NETCOUNTERAMOUNT = "NetCounterAmount"
TRADEFX = "tradeFX"
CONTRACTFXRATENUMERATOR = "ContractFxRateNumerator"
CONTRACTFXRATEDENOMINATOR = "ContractFxRateDenominator"
CONTRACTFXRATE = "ContractFxRate"
NOTIONALAMOUNT = "NotionalAmount"
FUNDSTRUCTURE2 = "FundStructure2"
SPOTDATE = "SpotDate"
PRICEDIRECTLY = "PriceDirectly"
COUNTERFXDENOMINATION = "CounterFXDenomination"
COUNTERTDATEFX = "CounterTDateFx"
ACCRUEDINTEREST = "AccruedInterest"
INVESTMENTACCRUEDINTEREST = "InvestmentAccruedInterest"
TRADEEXPENSES_EXPENSENUMBER = "TradeExpenses.ExpenseNumber"
TRADEEXPENSES_EXPENSECODE = "TradeExpenses.ExpenseCode"
TRADEEXPENSES_EXPENSEAMT = "TradeExpenses.ExpenseAmt"
NONCAPEXPENSES_NONCAPNUMBER = "NonCapExpenses.NonCapNumber"
NONCAPEXPENSES_NONCAPEXPENSECODE = "NonCapExpenses.NonCapExpenseCode"
NONCAPEXPENSES_NONCAPAMOUNT = "NonCapExpenses.NonCapAmount"
NONCAPEXPENSES_NONCAPCURRENCY = "NonCapExpenses.NonCapCurrency"
NONCAPEXPENSES_LOCATIONACCOUNT = "NonCapExpenses.LocationAccount"
NONCAPEXPENSES_NONCAPLIABILITYCODE = "NonCapExpenses.NonCapLiabilityCode"
NONCAPEXPENSES_NONCAPPAYMENTTYPE = "NonCapExpenses.NonCapPaymentType"


# ASIO SF-2 Price FNO
RECORDACTION = "RecordAction" 
PRICEDATE = "PriceDate" 
INVESTMENT = "Investment" 
PRICE = "Price" 
PRICEDENOMINATION = "PriceDenomination" 
PRICELIST = "PriceList" 
TAXLOTID = "TaxLotID" 

# Asio-Futture 03.09.2025, Asio-Futture 29.08.2025, Option 01-09-2025
CODE = "Code"
KEYVALUE = "KeyValue"
DESCRIPTION = "Description"
EXTENDEDDESCRIPTION = "ExtendedDescription"
EXCHANGE = "Exchange"
ISSUER = "Issuer"
TICKER = "Ticker"
CUSIP = "Cusip"
SEDOL = "Sedol"
ISIN = "Isin"
ALTKEY1 = "AltKey1"
ALTKEY2 = "AltKey2"
BLOOMBERGID = "BloombergID"
BLOOMBERGTICKER = "BloombergTicker"
BLOOMBERGUNIQUEID = "BloombergUniqueID"
BLOOMBERGMARKETSECTOR = "BloombergMarketSector"
SETTLEDAYS = "SettleDays"
PRICINGFACTOR = "PricingFactor"
TRADINGFACTOR = "TradingFactor"
CURRENTPRICEDAYRANGE = "CurrentPriceDayRange"
ASSETTYPE = "AssetType"
INVESTMENTTYPE = "InvestmentType"
PRICEDENOMINATION = "PriceDenomination"
BIFURCATIONCURRENCY = "BifurcationCurrency"
PRINCIPALCURRENCY = "PrincipalCurrency"
INCOMECURRENCY = "IncomeCurrency"
RISKCURRENCY = "RiskCurrency"
ISSUECOUNTRY = "IssueCountry"
WITHHOLDINGTAXTYPE = "WithholdingTaxType"
QDIELIGIBILITYFLAG = "QDIEligibilityFlag"
SHARESOUTSTANDING = "SharesOutstanding"
SUBINDUSTRY = "SubIndustry"
SUBINDUSTRY2 = "SubIndustry2"
QUANTITYPRECISION = "QuantityPrecision"
INVESTMENTCROSSZERO = "InvestmentCrossZero"
UNDERLYINGINVESTMENT = "UnderlyingInvestment"
EXPIREDATE = "ExpireDate"
STRIKEPRICE = "StrikePrice"
PRICEBYPREFERENCE = "PriceByPreference"
FORWARDPRICEINTERPOLATEFLAG = "ForwardPriceInterpolateFlag"
PRICINGPRECISION = "PricingPrecision"
FIRSTMARKDATE = "FirstMarkDate"
LASTMARKDATE = "LastMarkDate"
PRICELIST = "PriceList"
AUTOGENERATEMARKS = "AutoGenerateMarks"
CASHSETTLEMENT = "CashSettlement"

# ASIO SF-2 Price MCX 01-09-2025
RECORDACTION = "RecordAction"
PRICEDATE = "PriceDate"
INVESTMENT = "Investment"
PRICE = "Price"
PRICEDENOMINATION = "PriceDenomination"
PRICELIST = "PriceList"
TAXLOTID = "TaxLotID"

# MCX Option 01-09-2025
CODE = "Code"
KEYVALUE = "KeyValue"
DESCRIPTION = "Description"
EXTENDEDDESCRIPTION = "ExtendedDescription"
EXCHANGE = "Exchange"
ISSUER = "Issuer"
TICKER = "Ticker"
CUSIP = "Cusip"
SEDOL = "Sedol"
ISIN = "Isin"
RICCODE = "Riccode"
ALTKEY1 = "AltKey1"
ALTKEY2 = "AltKey2"
BLOOMBERGID = "BloombergID"
BLOOMBERGTICKER = "BloombergTicker"
BLOOMBERGUNIQUEID = "BloombergUniqueID"
BLOOMBERGMARKETSECTOR = "BloombergMarketSector"
SETTLEDAYS = "SettleDays"
PRICINGFACTOR = "PricingFactor"
TRADINGFACTOR = "TradingFactor"
CURRENTPRICEDAYRANGE = "CurrentPriceDayRange"
ASSETTYPE = "AssetType"
INVESTMENTTYPE = "InvestmentType"
PRICEDENOMINATION = "PriceDenomination"
BIFURCATIONCURRENCY = "BifurcationCurrency"
PRINCIPALCURRENCY = "PrincipalCurrency"
INCOMECURRENCY = "IncomeCurrency"
RISKCURRENCY = "RiskCurrency"
ISSUECOUNTRY = "IssueCountry"
WITHHOLDINGTAXTYPE = "WithholdingTaxType"
QDIELIGIBILITYFLAG = "QDIEligibilityFlag"
SHARESOUTSTANDING = "SharesOutstanding"
BETA = "Beta"
SUBINDUSTRY = "SubIndustry"
SUBINDUSTRY2 = "SubIndustry2"
NONDELIVERABLECURRENCYFLAG = "NonDeliverableCurrencyFlag"
QUANTITYPRECISION = "QuantityPrecision"
INVESTMENTCROSSZERO = "InvestmentCrossZero"
UNDERLYINGINVESTMENT = "UnderlyingInvestment"
EXPIREDATE = "ExpireDate"
STRIKEPRICE = "StrikePrice"
PRICEBYPREFERENCE = "PriceByPreference"
FORWARDPRICEINTERPOLATEFLAG = "ForwardPriceInterpolateFlag"
SECFEESCHEDULE = "SecFeeSchedule"
SECELIGIBLEFLAG = "SecEligibleFlag"
WASHSALESELIGIBLE = "WashSalesEligible"
EXERCISESTYLE = "ExerciseStyle"
PUTCALLFLAG = "PutCallFlag"
PRICINGPRECISION = "PricingPrecision"
CASHSETTLEDFLAG = "CashSettledFlag"

# MCX Option Trade Loader - ASIO SF 2  01-09-2025

RECORDTYPE = "RecordType"
RECORDACTION = "RecordAction"
KEYVALUE = "KeyValue"
KEYVALUE_KEYNAME = "KeyValue.KeyName"
USERTRANID1 = "UserTranId1"
PORTFOLIO = "Portfolio"
LOCATIONACCOUNT = "LocationAccount"
STRATEGY = "Strategy"
INVESTMENT = "Investment"
BROKER = "Broker"
EVENTDATE = "EventDate"
SETTLEDATE = "SettleDate"
ACTUALSETTLEDATE = "ActualSettleDate"
QUANTITY = "Quantity"
PRICE = "Price"
PRICEDENOMINATION = "PriceDenomination"
COUNTERINVESTMENT = "CounterInvestment"
NETINVESTMENTAMOUNT = "NetInvestmentAmount"
NETCOUNTERAMOUNT = "NetCounterAmount"
TRADEFX = "tradeFX"
CONTRACTFXRATENUMERATOR = "ContractFxRateNumerator"
CONTRACTFXRATEDENOMINATOR = "ContractFxRateDenominator"
CONTRACTFXRATE = "ContractFxRate"
NOTIONALAMOUNT = "NotionalAmount"
FUNDSTRUCTURE2 = "FundStructure2"
SPOTDATE = "SpotDate"
PRICEDIRECTLY = "PriceDirectly"
COUNTERFXDENOMINATION = "CounterFXDenomination"
COUNTERTDATEFX = "CounterTDateFx"
ACCRUEDINTEREST = "AccruedInterest"
INVESTMENTACCRUEDINTEREST = "InvestmentAccruedInterest"
TRADEEXPENSES_EXPENSENUMBER = "TradeExpenses.ExpenseNumber"
TRADEEXPENSES_EXPENSECODE = "TradeExpenses.ExpenseCode"
TRADEEXPENSES_EXPENSEAMT = "TradeExpenses.ExpenseAmt"
NONCAPEXPENSES_NONCAPNUMBER = "NonCapExpenses.NonCapNumber"
NONCAPEXPENSES_NONCAPEXPENSECODE = "NonCapExpenses.NonCapExpenseCode"
NONCAPEXPENSES_NONCAPAMOUNT = "NonCapExpenses.NonCapAmount"
NONCAPEXPENSES_NONCAPCURRENCY = "NonCapExpenses.NonCapCurrency"
NONCAPEXPENSES_LOCATIONACCOUNT = "NonCapExpenses.LocationAccount"
NONCAPEXPENSES_NONCAPLIABILITYCODE = "NonCapExpenses.NonCapLiabilityCode"
NONCAPEXPENSES_NONCAPPAYMENTTYPE = "NonCapExpenses.NonCapPaymentType"